export const planets = [
    
  { 
      name: 'Merkury', 
      modelPath: '/models/merkury_animacja.glb', 
      description: 'Pierwsza i najmniejsza planeta układu słonecznego, cechuje się największymi wachaniami temperatury w Układzie Słonecznym.' ,
      mass:'3.30 × 10²³ kg (0.055 Ziemi)',
      diameter:'4,880 km',
      hfar:'57.91 mln km (0.39 AU)',
      atmospheree:'Bardzo rzadka: sód, wodór, hel',
      temp:'-180°C do 430°C',
      dlength:'59 dni',
      ylength:'88 dni',
      moons:'',
      geology:'Kraterowa powierzchnia, brak wulkanów'
    },
    { 
      name: 'Wenus', 
      modelPath: '/models/ziema_animacja.glb', 
      description: 'Pierwsza i najmniejsza planeta układu słonecznego, cechuje się największymi wachaniami temperatury w Układzie Słonecznym.' ,
      mass:'4.87 × 10²⁴ kg (0.815 Ziemi)',
      diameter:'12,104 km',
      hfar:'108.2 mln km (0.72 AU)',
      atmospheree:'Gęsta: dwutlenek węgla, azot',
      temp:'Średnio 464°C',
      dlength:'243 dni (wstecz)',
      ylength:'225 dni',
      moons:'',
      geology:'Wulkany, równiny, gruba warstwa chmur kwasu siarkowego'
    },
    { 
      name: 'Ziemia', 
      modelPath: '/models/ziema_animacja.glb', 
      description: 'Pierwsza i najmniejsza planeta układu słonecznego, cechuje się największymi wachaniami temperatury w Układzie Słonecznym.' ,
      mass:'5.97 × 10²⁴ kg',
      diameter:'12,742 km',
      hfar:'149.6 mln km (1 AU)',
      atmospheree:'Azot (78%), tlen (21%), inne',
      temp:'Średnio 15°C',
      dlength:'24 godziny',
      ylength:'365 dni',
      moons:'1 (Księżyc)',
      geology:'Oceany (70%), góry, równiny, aktywne wulkany'
    },
    
    { 
      name: 'Mars', 
      modelPath: '/models/mars_animacja.glb', 
      description: 'Czwarta planeta układu słonecznego, znana ze swoich gór i kanionów, najększych w Układzie Słonecznym ' ,
      mass:'6.42 × 10²³ kg (0.107 Ziemi)',
      diameter:'6,779 km',
      hfar:'227.9 mln km (1.52 AU)',
      atmospheree:'Dwutlenek węgla (95%), azot, argon',
      temp:'-125°C do 20°C',
      dlength:'24.6 godziny',
      ylength:'687 dni',
      moons:'2 (Fobos, Deimos)',
      geology:'Wulkany (Olympus Mons), kaniony (Valles Marineris), polarne czapy lodowe'
    },
    { 
      name: 'Jowisz', 
      modelPath: '/models/jowisz_animacja.glb', 
      description: 'Pirwsza co do wielkości i masy planeta w Układzie Słonecznym .' ,
      mass:'1.90 × 10²⁷ kg (318 Ziemi)',
      diameter:'139,820 km',
      hfar:'778.5 mln km (5.2 AU)',
      atmospheree:'Wodór (90%), hel (10%)',
      temp:'-145°C',
      dlength:'9.9 godziny',
      ylength:'11.86 lat',
      moons:'95 (np. Io, Europa, Ganimedes)',
      geology:'Gazowy olbrzym, Wielka Czerwona Plama (ogromny antycyklon)'
    },
    { 
      name: 'Saturn', 
      modelPath: '/models/saturn_animacja.glb', 
      description: 'Spektakularne pierścienie czynią Saturna zapierającą dech w piersiach planetę' ,
      mass:'5.68 × 10²⁶ kg (95 Ziemi)',
      diameter:'116,460 km',
      hfar:'1.43 mld km (9.58 AU)',
      atmospheree:'Wodór (96%), hel (3%)',
      temp:'-178°C',
      dlength:'10.7 godziny',
      ylength:'29.46 lat',
      moons:'145 (np. Tytan, Enceladus)',
      geology:'Gazowy olbrzym z pierścieniami złożonymi z lodu i skał'
    },
    { 
      name: 'Uran', 
      modelPath: '/models/uran_animacja.glb', 
      description: 'Zaskakująca oś obrotu Uranu nachylona pod kątem 98°, sprawia, że planeta daje wrażenie jakby toczyła się po orbicie ' ,
      mass:'8.68 × 10²⁵ kg (14.5 Ziemi)',
      diameter:'50,724 km',
      hfar:'Wodór (83%), hel (15%), metan',
      atmospheree:'-224°C',
      temp:'-224°C',
      dlength:'17.2 godziny',
      ylength:'84 lata',
      moons:'27 (np. Miranda, Titania)',
      geology:'Lodowy olbrzym, metan nadaje niebiesko-zielony kolor'
    },
    { 
      name: 'Neptun', 
      modelPath: '/models/neptun_animacja.glb', 
      description: 'Ostatnie planeta Układu Słonecznego, cechujący się najsilniejszymi wiatrami w Układzie.' ,
      mass:'1.02 × 10²⁶ kg (17 Ziemi)',
      diameter:'49,244 km',
      hfar:'4.5 mld km (30.07 AU)',
      atmospheree:'Wodór (80%), hel (19%), metan',
      temp:'-218°C',
      dlength:'16.1 godziny',
      ylength:'164.8 lat',
      moons:'14 (np. Tryton)',
      geology:'Lodowy olbrzym, wiatry osiągają prędkość do 2,100 km/h'
    },
     
  ];